export enum EListItemActivityStateTypes {
  "SET_ERROR_INFO" = "SET_ERROR_INFO",
  "SET_ACTIVITIES" = "SET_ACTIVITIES",
  "SET_IS_LOADING" = "SET_IS_LOADING",
  "SET_VISIBLE_COUNT" = "SET_VISIBLE_COUNT",
}
