export enum EListItemActivityStateTypes {
  "SET_ERROR_INFO" = "SET_ERROR_INFO",
  "SET_ACTIVITIES" = "SET_ACTIVITIES",
  "SET_IS_LOADING" = "SET_IS_LOADING",
  "SET_IS_LOADING_MORE" = "SET_IS_LOADING_MORE",
  "SET_PAGE_INFO" = "SET_PAGE_INFO",
  "SET_V1_STATS" = "SET_V1_STATS",
  "SET_VISIBLE_COUNT" = "SET_VISIBLE_COUNT",
}
